# Generated by Django 4.2.6 on 2023-10-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_author_followers_books_author_books_genre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['-published_date', 'price']},
        ),
        migrations.AddField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(related_name='followed_authors', to='books.user'),
        ),
    ]
